name: Generate Snake Animation

on:
  push:
    branches:
      - main  # Change this to your default branch name if it's different
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours

jobs:
  generate_snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt  # Change this command to install any required dependencies for your snake generation script

      - name: Generate snake SVG
        run: python generate_snake.py  # Replace 'generate_snake.py' with the name of your snake generation script

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate snake SVG
          branch: main  # Change this to the branch where you want to push the changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
